name: terrascan
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tfsec:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true 

    - uses: github/codeql-action/upload-sarif@v3
      if: github.ref == 'refs/heads/master'
      with:
        sarif_file: terrascan.sarif
